name: mysql_cli_wrapper
version: 1.0.0
description: A sample command-line application.
environment: 
  sdk: ^3.0.2
dependencies: 
  dcli: ^3.0.2
  lint_hard: ^4.0.0
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.0
